# Generated by Django 5.0.3 on 2024-03-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
