# Generated by Django 5.0.3 on 2024-03-20 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comit', '0002_alter_mymodel_id_alter_mymodel_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='comit_apps',
        ),
    ]
