# Generated by Django 5.0.3 on 2024-03-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comit', '0003_rename_mymodel_comit_apps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comit_apps',
            new_name='apps',
        ),
    ]
