# Generated by Django 5.0.3 on 2024-03-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comit', '0004_rename_comit_apps_apps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='icon_link',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='apps',
            name='link',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
