# Generated by Django 5.0.3 on 2024-03-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comit', '0005_alter_apps_icon_link_alter_apps_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
